# Generated by Django 6.0.7 on 2026-09-03 14:12
# Migration de synchronisation d'état (pas de changement de schéma réel) :
# Django 6 normalise différemment les valeurs par défaut/choices déjà déclarées
# dans models.py (Etudiant.solde, Notification.type_notif), sans rapport avec
# l'ajout de ContactMessage. Séparée pour ne pas mélanger les deux sujets.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0028_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('nouveau_cours', 'Nouveau cours dans votre domaine'), ('nouvelle_ressource', 'Nouvelle ressource sur votre cours'), ('quiz_corrige', 'Quiz corrigé automatiquement')], default='nouveau_cours', max_length=50),
        ),
    ]
