# Generated by Django 6.0.7 on 2026-09-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0029_alter_etudiant_solde_alter_notification_type_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
